"""NeetCode 150 in roadmap order: (number, topic_number, topic, title, leetcode_slug, leetcode_premium)."""

PROBLEMS = [
    (1, 1, "Arrays & Hashing", "Contains Duplicate", "contains-duplicate", False),
    (2, 1, "Arrays & Hashing", "Valid Anagram", "valid-anagram", False),
    (3, 1, "Arrays & Hashing", "Two Sum", "two-sum", False),
    (4, 1, "Arrays & Hashing", "Group Anagrams", "group-anagrams", False),
    (5, 1, "Arrays & Hashing", "Top K Frequent Elements", "top-k-frequent-elements", False),
    (6, 1, "Arrays & Hashing", "Encode and Decode Strings", "encode-and-decode-strings", True),
    (7, 1, "Arrays & Hashing", "Product of Array Except Self", "product-of-array-except-self", False),
    (8, 1, "Arrays & Hashing", "Valid Sudoku", "valid-sudoku", False),
    (9, 1, "Arrays & Hashing", "Longest Consecutive Sequence", "longest-consecutive-sequence", False),
    (10, 2, "Two Pointers", "Valid Palindrome", "valid-palindrome", False),
    (11, 2, "Two Pointers", "Two Sum II", "two-sum-ii-input-array-is-sorted", False),
    (12, 2, "Two Pointers", "3Sum", "3sum", False),
    (13, 2, "Two Pointers", "Container With Most Water", "container-with-most-water", False),
    (14, 2, "Two Pointers", "Trapping Rain Water", "trapping-rain-water", False),
    (15, 3, "Sliding Window", "Best Time to Buy and Sell Stock", "best-time-to-buy-and-sell-stock", False),
    (16, 3, "Sliding Window", "Longest Substring Without Repeating Characters", "longest-substring-without-repeating-characters", False),
    (17, 3, "Sliding Window", "Longest Repeating Character Replacement", "longest-repeating-character-replacement", False),
    (18, 3, "Sliding Window", "Permutation in String", "permutation-in-string", False),
    (19, 3, "Sliding Window", "Minimum Window Substring", "minimum-window-substring", False),
    (20, 3, "Sliding Window", "Sliding Window Maximum", "sliding-window-maximum", False),
    (21, 4, "Stack", "Valid Parentheses", "valid-parentheses", False),
    (22, 4, "Stack", "Min Stack", "min-stack", False),
    (23, 4, "Stack", "Evaluate Reverse Polish Notation", "evaluate-reverse-polish-notation", False),
    (24, 4, "Stack", "Generate Parentheses", "generate-parentheses", False),
    (25, 4, "Stack", "Daily Temperatures", "daily-temperatures", False),
    (26, 4, "Stack", "Car Fleet", "car-fleet", False),
    (27, 4, "Stack", "Largest Rectangle in Histogram", "largest-rectangle-in-histogram", False),
    (28, 5, "Binary Search", "Binary Search", "binary-search", False),
    (29, 5, "Binary Search", "Search a 2D Matrix", "search-a-2d-matrix", False),
    (30, 5, "Binary Search", "Koko Eating Bananas", "koko-eating-bananas", False),
    (31, 5, "Binary Search", "Find Minimum in Rotated Sorted Array", "find-minimum-in-rotated-sorted-array", False),
    (32, 5, "Binary Search", "Search in Rotated Sorted Array", "search-in-rotated-sorted-array", False),
    (33, 5, "Binary Search", "Time Based Key-Value Store", "time-based-key-value-store", False),
    (34, 5, "Binary Search", "Median of Two Sorted Arrays", "median-of-two-sorted-arrays", False),
    (35, 6, "Linked List", "Reverse Linked List", "reverse-linked-list", False),
    (36, 6, "Linked List", "Merge Two Sorted Lists", "merge-two-sorted-lists", False),
    (37, 6, "Linked List", "Reorder List", "reorder-list", False),
    (38, 6, "Linked List", "Remove Nth Node From End of List", "remove-nth-node-from-end-of-list", False),
    (39, 6, "Linked List", "Copy List with Random Pointer", "copy-list-with-random-pointer", False),
    (40, 6, "Linked List", "Add Two Numbers", "add-two-numbers", False),
    (41, 6, "Linked List", "Linked List Cycle", "linked-list-cycle", False),
    (42, 6, "Linked List", "Find the Duplicate Number", "find-the-duplicate-number", False),
    (43, 6, "Linked List", "LRU Cache", "lru-cache", False),
    (44, 6, "Linked List", "Merge k Sorted Lists", "merge-k-sorted-lists", False),
    (45, 6, "Linked List", "Reverse Nodes in k-Group", "reverse-nodes-in-k-group", False),
    (46, 7, "Trees", "Invert Binary Tree", "invert-binary-tree", False),
    (47, 7, "Trees", "Maximum Depth of Binary Tree", "maximum-depth-of-binary-tree", False),
    (48, 7, "Trees", "Diameter of Binary Tree", "diameter-of-binary-tree", False),
    (49, 7, "Trees", "Balanced Binary Tree", "balanced-binary-tree", False),
    (50, 7, "Trees", "Same Tree", "same-tree", False),
    (51, 7, "Trees", "Subtree of Another Tree", "subtree-of-another-tree", False),
    (52, 7, "Trees", "Lowest Common Ancestor of a BST", "lowest-common-ancestor-of-a-binary-search-tree", False),
    (53, 7, "Trees", "Binary Tree Level Order Traversal", "binary-tree-level-order-traversal", False),
    (54, 7, "Trees", "Binary Tree Right Side View", "binary-tree-right-side-view", False),
    (55, 7, "Trees", "Count Good Nodes in Binary Tree", "count-good-nodes-in-binary-tree", False),
    (56, 7, "Trees", "Validate Binary Search Tree", "validate-binary-search-tree", False),
    (57, 7, "Trees", "Kth Smallest Element in a BST", "kth-smallest-element-in-a-bst", False),
    (58, 7, "Trees", "Construct Binary Tree from Preorder and Inorder", "construct-binary-tree-from-preorder-and-inorder-traversal", False),
    (59, 7, "Trees", "Binary Tree Maximum Path Sum", "binary-tree-maximum-path-sum", False),
    (60, 7, "Trees", "Serialize and Deserialize Binary Tree", "serialize-and-deserialize-binary-tree", False),
    (61, 8, "Heap / Priority Queue", "Kth Largest Element in a Stream", "kth-largest-element-in-a-stream", False),
    (62, 8, "Heap / Priority Queue", "Last Stone Weight", "last-stone-weight", False),
    (63, 8, "Heap / Priority Queue", "K Closest Points to Origin", "k-closest-points-to-origin", False),
    (64, 8, "Heap / Priority Queue", "Kth Largest Element in an Array", "kth-largest-element-in-an-array", False),
    (65, 8, "Heap / Priority Queue", "Task Scheduler", "task-scheduler", False),
    (66, 8, "Heap / Priority Queue", "Design Twitter", "design-twitter", False),
    (67, 8, "Heap / Priority Queue", "Find Median from Data Stream", "find-median-from-data-stream", False),
    (68, 9, "Backtracking", "Subsets", "subsets", False),
    (69, 9, "Backtracking", "Combination Sum", "combination-sum", False),
    (70, 9, "Backtracking", "Permutations", "permutations", False),
    (71, 9, "Backtracking", "Subsets II", "subsets-ii", False),
    (72, 9, "Backtracking", "Combination Sum II", "combination-sum-ii", False),
    (73, 9, "Backtracking", "Word Search", "word-search", False),
    (74, 9, "Backtracking", "Palindrome Partitioning", "palindrome-partitioning", False),
    (75, 9, "Backtracking", "Letter Combinations of a Phone Number", "letter-combinations-of-a-phone-number", False),
    (76, 9, "Backtracking", "N-Queens", "n-queens", False),
    (77, 10, "Tries", "Implement Trie", "implement-trie-prefix-tree", False),
    (78, 10, "Tries", "Design Add and Search Words", "design-add-and-search-words-data-structure", False),
    (79, 10, "Tries", "Word Search II", "word-search-ii", False),
    (80, 11, "Graphs", "Number of Islands", "number-of-islands", False),
    (81, 11, "Graphs", "Clone Graph", "clone-graph", False),
    (82, 11, "Graphs", "Max Area of Island", "max-area-of-island", False),
    (83, 11, "Graphs", "Pacific Atlantic Water Flow", "pacific-atlantic-water-flow", False),
    (84, 11, "Graphs", "Surrounded Regions", "surrounded-regions", False),
    (85, 11, "Graphs", "Rotting Oranges", "rotting-oranges", False),
    (86, 11, "Graphs", "Walls and Gates", "walls-and-gates", True),
    (87, 11, "Graphs", "Course Schedule", "course-schedule", False),
    (88, 11, "Graphs", "Course Schedule II", "course-schedule-ii", False),
    (89, 11, "Graphs", "Redundant Connection", "redundant-connection", False),
    (90, 11, "Graphs", "Number of Connected Components", "number-of-connected-components-in-an-undirected-graph", True),
    (91, 11, "Graphs", "Graph Valid Tree", "graph-valid-tree", True),
    (92, 11, "Graphs", "Word Ladder", "word-ladder", False),
    (93, 12, "Advanced Graphs", "Reconstruct Itinerary", "reconstruct-itinerary", False),
    (94, 12, "Advanced Graphs", "Min Cost to Connect All Points", "min-cost-to-connect-all-points", False),
    (95, 12, "Advanced Graphs", "Network Delay Time", "network-delay-time", False),
    (96, 12, "Advanced Graphs", "Swim in Rising Water", "swim-in-rising-water", False),
    (97, 12, "Advanced Graphs", "Alien Dictionary", "alien-dictionary", True),
    (98, 12, "Advanced Graphs", "Cheapest Flights Within K Stops", "cheapest-flights-within-k-stops", False),
    (99, 13, "1-D DP", "Climbing Stairs", "climbing-stairs", False),
    (100, 13, "1-D DP", "Min Cost Climbing Stairs", "min-cost-climbing-stairs", False),
    (101, 13, "1-D DP", "House Robber", "house-robber", False),
    (102, 13, "1-D DP", "House Robber II", "house-robber-ii", False),
    (103, 13, "1-D DP", "Longest Palindromic Substring", "longest-palindromic-substring", False),
    (104, 13, "1-D DP", "Palindromic Substrings", "palindromic-substrings", False),
    (105, 13, "1-D DP", "Decode Ways", "decode-ways", False),
    (106, 13, "1-D DP", "Coin Change", "coin-change", False),
    (107, 13, "1-D DP", "Maximum Product Subarray", "maximum-product-subarray", False),
    (108, 13, "1-D DP", "Word Break", "word-break", False),
    (109, 13, "1-D DP", "Longest Increasing Subsequence", "longest-increasing-subsequence", False),
    (110, 13, "1-D DP", "Partition Equal Subset Sum", "partition-equal-subset-sum", False),
    (111, 14, "2-D DP", "Unique Paths", "unique-paths", False),
    (112, 14, "2-D DP", "Longest Common Subsequence", "longest-common-subsequence", False),
    (113, 14, "2-D DP", "Buy and Sell Stock with Cooldown", "best-time-to-buy-and-sell-stock-with-cooldown", False),
    (114, 14, "2-D DP", "Coin Change II", "coin-change-ii", False),
    (115, 14, "2-D DP", "Target Sum", "target-sum", False),
    (116, 14, "2-D DP", "Interleaving String", "interleaving-string", False),
    (117, 14, "2-D DP", "Longest Increasing Path in a Matrix", "longest-increasing-path-in-a-matrix", False),
    (118, 14, "2-D DP", "Distinct Subsequences", "distinct-subsequences", False),
    (119, 14, "2-D DP", "Edit Distance", "edit-distance", False),
    (120, 14, "2-D DP", "Burst Balloons", "burst-balloons", False),
    (121, 14, "2-D DP", "Regular Expression Matching", "regular-expression-matching", False),
    (122, 15, "Greedy", "Maximum Subarray", "maximum-subarray", False),
    (123, 15, "Greedy", "Jump Game", "jump-game", False),
    (124, 15, "Greedy", "Jump Game II", "jump-game-ii", False),
    (125, 15, "Greedy", "Gas Station", "gas-station", False),
    (126, 15, "Greedy", "Hand of Straights", "hand-of-straights", False),
    (127, 15, "Greedy", "Merge Triplets to Form Target Triplet", "merge-triplets-to-form-target-triplet", False),
    (128, 15, "Greedy", "Partition Labels", "partition-labels", False),
    (129, 15, "Greedy", "Valid Parenthesis String", "valid-parenthesis-string", False),
    (130, 16, "Intervals", "Insert Interval", "insert-interval", False),
    (131, 16, "Intervals", "Merge Intervals", "merge-intervals", False),
    (132, 16, "Intervals", "Non-overlapping Intervals", "non-overlapping-intervals", False),
    (133, 16, "Intervals", "Meeting Rooms", "meeting-rooms", True),
    (134, 16, "Intervals", "Meeting Rooms II", "meeting-rooms-ii", True),
    (135, 16, "Intervals", "Minimum Interval to Include Each Query", "minimum-interval-to-include-each-query", False),
    (136, 17, "Math & Geometry", "Rotate Image", "rotate-image", False),
    (137, 17, "Math & Geometry", "Spiral Matrix", "spiral-matrix", False),
    (138, 17, "Math & Geometry", "Set Matrix Zeroes", "set-matrix-zeroes", False),
    (139, 17, "Math & Geometry", "Happy Number", "happy-number", False),
    (140, 17, "Math & Geometry", "Plus One", "plus-one", False),
    (141, 17, "Math & Geometry", "Pow(x, n)", "powx-n", False),
    (142, 17, "Math & Geometry", "Multiply Strings", "multiply-strings", False),
    (143, 17, "Math & Geometry", "Detect Squares", "detect-squares", False),
    (144, 18, "Bit Manipulation", "Single Number", "single-number", False),
    (145, 18, "Bit Manipulation", "Number of 1 Bits", "number-of-1-bits", False),
    (146, 18, "Bit Manipulation", "Counting Bits", "counting-bits", False),
    (147, 18, "Bit Manipulation", "Reverse Bits", "reverse-bits", False),
    (148, 18, "Bit Manipulation", "Missing Number", "missing-number", False),
    (149, 18, "Bit Manipulation", "Sum of Two Integers", "sum-of-two-integers", False),
    (150, 18, "Bit Manipulation", "Reverse Integer", "reverse-integer", False),
]
